spring.application.name=BCh_System

spring.jpa.hibernate.ddl-auto=create
spring.datasource.url=jdbc:mysql://${MYSQL_HOST:localhost}:3306/testsevaluationsystem
spring.datasource.username=userspring
spring.datasource.password=${PASSWORD}
spring.datasource.driver-class-name =com.mysql.cj.jdbc.Driver
server.port=8081
#--------------------------------------------------------------------
spring.jpa.open-in-view=false

#Will be enabled, just not to see the warning
spring.thymeleaf.check-template-location=false 

